name: docker-build-branch

on:
  push:
    branches-ignore:
    - 'master'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build and push docker images
      run: |
        for dir in docker/*; do
          tool_name=$(echo "$dir" | awk '{print tolower($0)}')
          for tag_dir in docker/"$dir"/*; do
            tag=branch-${GITHUB_REF##*/}-$tag_dir
            docker build -t stjudecloud/"$tool_name":"$tag" docker/"$dir"/"$tag_dir"
            docker push stjudecloud/"$tool_name":"$tag"
          done
        done