name: import-check

on: [push]

jobs:
  import_syntax_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check import syntax
      run: |
        files=$(find . -name '*.wdl')
        bad_lines=$(awk '/import/' $files | \
          awk '!/https:\/\/raw.githubusercontent.com\/stjudecloud\/workflows\/master/')
        if [ -n "$bad_lines" ]; then
          echo "$bad_lines"
          exit 1
        fi